USE restaurant_search;

INSERT INTO restaurants (name, city) VALUES
('Hyderabadi Spice House', 'Hyderabad'),
('Biryani Palace', 'Hyderabad'),
('Spice Route Kitchen', 'Bengaluru'),
('Delhi Zaika', 'Delhi'),
('Mumbai Masala', 'Mumbai'),
('Kolkata Kuisine', 'Kolkata'),
('Chennai Chettinad', 'Chennai'),
('Lucknow Nawabi', 'Lucknow'),
('Pune Tadka', 'Pune'),
('Jaipur Rasoi', 'Jaipur'),
('Kochi Curry Leaf', 'Kochi');


INSERT INTO menu_items (restaurant_id, dish_name, price) VALUES
(1, 'Chicken Biryani', 220),
(1, 'Mutton Biryani', 320),
(2, 'Chicken Biryani', 180),
(2, 'Veg Biryani', 150),
(3, 'Chicken Biryani', 260),
(3, 'Paneer Butter Masala', 240),
(4, 'Chicken Biryani', 310),
(4, 'Dal Makhani', 200),
(5, 'Chicken Biryani', 240),
(5, 'Butter Chicken', 280),
(6, 'Chicken Biryani', 210),
(6, 'Fish Curry', 260),
(7, 'Chicken Biryani', 230),
(7, 'Dosa', 120),
(8, 'Chicken Biryani', 200),
(8, 'Kebab Platter', 350),
(9, 'Chicken Biryani', 190),
(9, 'Misal Pav', 110),
(10, 'Chicken Biryani', 170),
(10, 'Laal Maas', 360),
(11, 'Chicken Biryani', 205),
(11, 'Appam Stew', 160);


INSERT INTO orders (menu_item_id) SELECT 1 FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) t1,
(SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6) t2,
(SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) t3;



INSERT INTO orders (menu_item_id) SELECT 3 FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) a,
(SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7) b;


INSERT INTO orders (menu_item_id) SELECT 3 FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) a,
(SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7) b;


INSERT INTO orders (menu_item_id) SELECT 5 FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) a,
(SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) b;



INSERT INTO orders (menu_item_id) SELECT 7 FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) a,
(SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8) b;



INSERT INTO orders (menu_item_id) SELECT 9 FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) a,
(SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13) b;



INSERT INTO orders (menu_item_id) SELECT 11 FROM (SELECT 1 UNION ALL SELECT 2) a,
(SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11) b;



INSERT INTO orders (menu_item_id) SELECT 13 FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3) a,
(SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6) b;



INSERT INTO orders (menu_item_id) SELECT 15 FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) a,
(SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11) b;



INSERT INTO orders (menu_item_id) SELECT 17 FROM (SELECT 1 UNION ALL SELECT 2) a,
(SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) b;



INSERT INTO orders (menu_item_id) SELECT 19 FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3) a,
(SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) b,
(SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) c;

INSERT INTO orders (menu_item_id) SELECT 21 FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3) a,
(SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11) b;

